apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: nginx
          imagePullPolicy: Always
          ports:
          - containerPort: 80
            name: web
            protocol: TCP
          env:
            - name: COW_COLOR
              value: green
          readinessProbe:
            httpGet:
              port: web
              path: /
